"""FR-D4 — deploy config validation (no hosting, no charges)."""
from __future__ import annotations

from pathlib import Path

import yaml

from app.prodcheck import insecure_env_keys, is_production_ready

_REPO_ROOT = Path(__file__).resolve().parents[2]
_RENDER_YAML = _REPO_ROOT / "render.yaml"


def _load_render() -> dict:
    return yaml.safe_load(_RENDER_YAML.read_text())


def test_render_blueprint_is_valid_and_complete() -> None:
    blueprint = _load_render()
    services = {s["name"]: s for s in blueprint["services"]}
    assert "olivo-backend" in services
    assert {"olivo-embed", "olivo-admin"} <= set(services)
    assert any(db["name"] == "olivo-postgres" for db in blueprint["databases"])

    backend = services["olivo-backend"]
    assert backend["healthCheckPath"] == "/health"
    env_keys = {e["key"] for e in backend["envVars"]}
    assert {"DATABASE_URL", "JWT_SECRET", "ANTHROPIC_API_KEY", "STRIPE_SECRET_KEY"} <= env_keys


def test_render_blueprint_commits_no_secret_values() -> None:
    backend = next(
        s for s in _load_render()["services"] if s["name"] == "olivo-backend"
    )
    for entry in backend["envVars"]:
        if entry["key"] in {
            "ANTHROPIC_API_KEY",
            "STRIPE_SECRET_KEY",
            "STRIPE_WEBHOOK_SECRET",
        }:
            # secrets must be dashboard-set, never a committed literal
            assert "value" not in entry
            assert entry.get("sync") is False
    # JWT_SECRET is generated by the platform, not committed
    jwt_entry = next(e for e in backend["envVars"] if e["key"] == "JWT_SECRET")
    assert jwt_entry.get("generateValue") is True
    assert "value" not in jwt_entry


def test_dev_defaults_are_flagged_as_insecure() -> None:
    dev_env = {
        "DATABASE_URL": "postgresql://olivo:olivo_dev_password@localhost:5432/olivo_chat",
        "JWT_SECRET": "change_me_to_random_64_chars_in_production",
        "ANTHROPIC_API_KEY": "sk-ant-placeholder",
        "STRIPE_SECRET_KEY": "sk_test_placeholder",
        "STRIPE_WEBHOOK_SECRET": "whsec_placeholder",
    }
    flagged = insecure_env_keys(dev_env)
    assert set(flagged) == set(dev_env)  # every dev value is rejected
    assert not is_production_ready(dev_env)


def test_realistic_prod_env_passes() -> None:
    prod_env = {
        "DATABASE_URL": "postgresql://olivo:Aa9f3kQ2@db.internal:5432/olivo_chat",
        "JWT_SECRET": "b1c4f8e2a7d9034516fe8c2b9a7d6e5f4c3b2a1908f7e6d5c4b3a2918",
        "ANTHROPIC_API_KEY": "sk-ant-api03-Zm9vYmFyYmF6",
        "STRIPE_SECRET_KEY": "sk_live_51AbCdEf",
        "STRIPE_WEBHOOK_SECRET": "whsec_9Xy2Lm",
    }
    assert insecure_env_keys(prod_env) == []
    assert is_production_ready(prod_env)


def test_missing_secret_is_flagged() -> None:
    assert "JWT_SECRET" in insecure_env_keys({"JWT_SECRET": ""})
